hydra:
  run:
    dir: .log/${mode}/${experiment.name}

mode: test

defaults:
  - config/experiment@experiment: default
  - config/distortion@distortion: identity

data:
  resol: 128
  gray: False
  msg_len: 30
  test_batch_size: 192 # 12
  root: /home/tanimu/data
  train_path: ${data.root}/coco2014_hidden/train
  test_path: ${data.root}/coco2014_hidden/test

experiment:
  tags: null
  use_comet: False
  model_path: ???
  relative_model_path: ../../../${experiment.model_path}

distortion:
  name: ???
  probability: 0.0
  probabilities: [0.0]
  kernel_size: 0
  sigma: 0.0
  sigmas: [0.0]
  quality_factor: 0
  parallelable: False

seed: 123
gpu_ids: 
  - 0
