hydra:
  run:
    dir: .log/${mode}/${experiment.name}

mode: test

defaults:
  - config/experiment@experiment: default

data:
  resol: 128
  gray: False
  msg_len: 30
  test_batch_size: 192 # 12
  root: /home/tanimu/data
  train_path: ${data.root}/coco2014/train
  test_path: ${data.root}/coco2014/test

experiment:
  tags: null
  use_comet: False
  model_path: ???
  relative_model_path: ../../../${experiment.model_path}

seed: 1234
gpu_ids: []
