hydra:
  run:
    dir: log/${mode}/${experiment.name}

mode: train

defaults:
  - config/experiment@experiment: default

data:
  resol: 128
  gray: False
  msg_len: 30
  batch_size: 12
  train_path: "/Users/tanimu/data/coco2014/test"
  test_path: "/Users/tanimu/data/coco2014/test"

training:
  epochs: 100
  test_interval: 10

experiment:
  tags: null
  resume_training: False
  use_comet: False
  resume_exp_key: null

seed: null
gpu_ids: []
