hydra:
  run:
    dir: log/${mode}/${experiment.name}

mode: train

defaults:
  - config/experiment@experiment: default
  - config/distortion@distortion: identity

data:
  resol: 128
  gray: False
  msg_len: 30
  train_batch_size: 48 # 12
  test_batch_size: 192 # 12
  train_path: /home/tanimu/data/coco2014/train
  test_path: /home/tanimu/data/coco2014/test

training:
  epochs: 100
  test_interval: 5
  lr_scheduler_milestones: [50]
  lr_scheduler_step_factor: 0.1

experiment:
  tags: null
  resume_training: False
  use_comet: False
  comet:
    resume_experiment_key: null

train:
  optimizer_lr: 1e-2 # 1e-3
  optimizer_wd: 0.0
  discriminator_lr: 1e-2 # 1e-3

distortion:
  name: ???
  probability: 0.0
  kernel_size: 0
  sigma: 0.0
  quality_factor: 0

seed: 1234
gpu_ids: []
