hydra:
  run:
    dir: .log/${mode}/${experiment.name}

mode: train

defaults:
  - config/experiment@experiment: default
  - config/distortion@train_distortion: identity
  - config/distortion@test_distortion: identity

data:
  resol: 128
  gray: False
  msg_len: 30
  train_batch_size: 48 # 12
  test_batch_size: 192 # 12
  root: /home/tanimu/data
  train_path: ${data.root}/coco2014/train
  test_path: ${data.root}/coco2014/test

training:
  epochs: 150
  test_interval: 5
  lr_scheduler_milestones: [100]
  lr_scheduler_step_factor: 0.1

experiment:
  tags: null
  resume_training: False
  use_comet: False
  comet:
    resume_experiment_key: null

train:
  optimizer_lr: 1e-3
  optimizer_wd: 0.0
  discriminator_lr: 1e-3

train_distortion:
  name: ???
  probability: 0.0
  kernel_size: 0
  sigma: 0.0
  quality_factor: 0
  paralellable: False

test_distortion:
  name: ???
  probability: 0.0
  kernel_size: 0
  sigma: 0.0
  quality_factor: 0
  paralellable: False

seed: 1234
gpu_ids: 
  - 0
  - 1
