hydra:
  run:
    dir: .log/${mode}/${experiment.name}

mode: train

defaults:
  - config/experiment@experiment: new
  - config/distortion@train_distortion: identity
  - config/distortion@test_distortion: identity
  - config/dataset@dataset: bit

data:
  resol: 128
  gray: False
  msg_len: 30
  train_batch_size: 48 # 12
  test_batch_size: 192 # 12
  root: /home/tanimu/data
  train_path: ${data.root}/coco2014/train
  test_path: ${data.root}/coco2014/test
  train_num_images: -1
  test_num_images: -1

training:
  epochs: 150
  test_interval: 5
  lr_scheduler_milestones: [100]
  lr_scheduler_step_factor: 0.1

train:
  optimizer_lr: 1e-3
  optimizer_wd: 0.0
  discriminator_lr: 1e-3

train_distortion:
  name: ???
  probability: 0.0
  probabilities: [0.0]
  kernel_size: 0
  sigma: 0.0
  sigmas: [0.0]
  quality_factor: 0
  parallelable: False

test_distortion:
  name: ???
  probability: 0.0
  probabilities: [0.0]
  kernel_size: 0
  sigma: 0.0
  sigmas: [0.0]
  quality_factor: 0
  parallelable: False

seed: null
gpu_ids: 
  - 0
