hydra:
  run:
    dir: log/${mode}/${experiment.name}

mode: train

defaults:
  - config/experiment@experiment: default

data:
  resol: 128
  gray: False
  msg_len: 30
  train_batch_size: 48 # 12
  test_batch_size: 192 # 12
  train_path: /home/tanimu/data/coco2014/train
  test_path: /home/tanimu/data/coco2014/test

training:
  epochs: 200
  test_interval: 10

experiment:
  tags: null
  resume_training: False
  use_comet: False
  comet:
    resume_experiment_key: null

train:
  optimizer_lr: 1e-2 # 1e-3
  optimizer_wd: 0.0
  discriminator_lr: 1e-2 # 1e-3

seed: null
gpu_ids: []
